name = "MeshViz"
uuid = "9ecf9c4f-6e5a-4b5e-83ae-06f2c7a661d8"
authors = ["JÃºlio Hoffimann <julio.hoffimann@gmail.com> and contributors"]
version = "0.1.3"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Makie = "0.13"
Meshes = "0.16"
Tables = "1.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
