name = "MeshViz"
uuid = "9ecf9c4f-6e5a-4b5e-83ae-06f2c7a661d8"
authors = ["JÃºlio Hoffimann <julio.hoffimann@gmail.com> and contributors"]
version = "0.3.2"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CategoricalArrays = "0.10"
Colors = "0.12"
Makie = "0.13, 0.14, 0.15, 0.16"
Meshes = "0.19"
Tables = "1.4"
julia = "1.6"